# Generated by Django 5.2.3 on 2025-06-16 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Auto-generated patient ID', max_length=20, unique=True)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('preferred_name', models.CharField(blank=True, max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('skin_type', models.CharField(blank=True, choices=[('I', 'Type I - Always burns, never tans'), ('II', 'Type II - Usually burns, tans minimally'), ('III', 'Type III - Sometimes burns, tans gradually'), ('IV', 'Type IV - Burns minimally, always tans well'), ('V', 'Type V - Very rarely burns, tans very easily'), ('VI', 'Type VI - Never burns, always tans darkly')], max_length=5)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('call', 'Phone Call')], default='email', max_length=10)),
                ('preferred_language', models.CharField(default='English', max_length=50)),
                ('insurance_provider', models.CharField(blank=True, max_length=100)),
                ('insurance_number', models.CharField(blank=True, max_length=50)),
                ('insurance_valid_until', models.DateField(blank=True, null=True)),
                ('referral_source', models.CharField(blank=True, choices=[('doctor', 'Doctor Referral'), ('friend', 'Friend/Family'), ('online', 'Online Search'), ('social_media', 'Social Media'), ('advertisement', 'Advertisement'), ('other', 'Other')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='patients.patient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients_patient',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('skin', 'Skin Condition'), ('allergy', 'Allergy'), ('surgery', 'Surgery'), ('medication', 'Medication'), ('family_history', 'Family History'), ('other', 'Other')], max_length=20)),
                ('condition_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_diagnosed', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient')),
            ],
            options={
                'db_table': 'patients_medical_history',
                'ordering': ['-date_diagnosed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id', 'ID Card'), ('insurance', 'Insurance Card'), ('medical_report', 'Medical Report'), ('prescription', 'Prescription'), ('lab_result', 'Lab Result'), ('consent_form', 'Consent Form'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='patient_documents/')),
                ('description', models.TextField(blank=True)),
                ('is_sensitive', models.BooleanField(default=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
